name: Push CI
permissions:
  contents: write
on:
  push:
    branches: [main]
    tags:
      - "v*"

jobs:
  lint_and_fast_tests:
    name: "Run CLI tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x, 17.x, 18.x, current]
    steps:
      # Basic setup
      - uses: actions/checkout@v3
        with:
          clean: "false"
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn turbo run build
      - name: Setup git
        run: git config --global user.email "test@gmail.com" && git config --global user.name "test"
      - name: Git Version
        run: git --version
      - name: Test
        run: yarn workspace @da1z/pancake run test

  superlinter:
    name: "Run superlinter"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        continue-on-error: true
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TYPESCRIPT_DEFAULT_STYLE: prettier

  create-binaries:
    name: Upload executable binaries
    strategy:
      matrix:
        os: [macos, ubuntu]
        include:
          - os: macos
            build: yarn workspace @da1z/pancake run build-pkg -t node18-macos -o "pk-macos-x86-${{ github.sha }}"
            artifact-name: pk-macos-x86-${{ github.sha }}
            artifact-path: apps/cli/pk-macos-x86-${{ github.sha }}
          - os: ubuntu
            build: yarn workspace @da1z/pancake run build-pkg -t node18-linux -o "pk-linux-${{ github.sha }}"
            artifact-name: pk-linux-${{ github.sha }}
            artifact-path: apps/cli/pk-linux-${{ github.sha }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn turbo run build
      - name: Build binary
        run: ${{ matrix.build }}
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.artifact-path }}

  release:
    name: Release version
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [lint_and_fast_tests, create-binaries]
    runs-on: ubuntu-latest
    steps:
      - name: Download mac x86
        uses: actions/download-artifact@v4
        with:
          name: pk-macos-x86-${{ github.sha }}
      - name: Download linux
        uses: actions/download-artifact@v4
        with:
          name: pk-linux-${{ github.sha }}
      - name: Rename files
        run: |
          mv pk-macos-x86-${{ github.sha }} pk-macos-x86;
          mv pk-linux-${{ github.sha }} pk-linux
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "pk-macos-x86,pk-linux"
          draft: false
          prerelease: true
          allowUpdates: true
